spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:change_me_32_chars_minimum_secret}
    cookie-secure: ${JWT_COOKIE_SECURE:false}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html